# Generated by Django 5.2.12 on 2026-03-13 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=500, unique=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('subject', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('from_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to='polls.employee')),
                ('to_employees', models.ManyToManyField(related_name='received_emails', to='polls.employee')),
            ],
        ),
    ]
