# Generated by Django 5.2.12 on 2026-03-14 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='email',
            name='bcc_employees',
            field=models.ManyToManyField(blank=True, related_name='bcc_emails', to='polls.employee'),
        ),
        migrations.AddField(
            model_name='email',
            name='cc_employees',
            field=models.ManyToManyField(blank=True, related_name='cc_emails', to='polls.employee'),
        ),
        migrations.AddField(
            model_name='email',
            name='in_reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='polls.email'),
        ),
        migrations.AlterField(
            model_name='email',
            name='to_employees',
            field=models.ManyToManyField(blank=True, related_name='received_emails', to='polls.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('content_type', models.CharField(blank=True, max_length=200)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='polls.email')),
            ],
        ),
        migrations.AddField(
            model_name='email',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.folder'),
        ),
    ]
