# Generated by Django 5.2.12 on 2026-03-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_folder_email_bcc_employees_email_cc_employees_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['date'], name='polls_email_date_a64820_idx'),
        ),
    ]
