# Generated by Django 5.2.12 on 2026-03-14 16:44

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_email_polls_email_date_a64820_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='email',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['message_id'], name='polls_email_message_8f8249_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='email_fts_gin_idx'),
        ),
    ]
